### ISSUE TITLE
Proxy setting might not work

### ISSUE THREAD

**Issue by siquylee** [atata-framework/atata-configuration-json#32]
Here is the content of Atata.json file
{
  "driver": {
    "type": "chrome",
    "options": {
      "arguments": [
        "incognito",
        "disable-3d-apis",
        "disable-accelerated-video",
        "disable-background-mode",
        "disable-gpu",
        "disable-plugins",
        "disable-plugins-discovery",
        "disable-translate",
        "disable-extensions",
        "start-maximized",
        "ignore-certificate-errors"
      ]
    },
    "proxy": {
      "kind": "Manual",
      "httpProxy": "127.0.0.1:8888",
      "sslProxy": "127.0.0.1:8888"
    }
  },
  "baseUrl": "https://www.google.com",
  "culture": "en-US",
  "logConsumers": [
    {
      "type": "console",
      "minLevel": "Trace",
      "sectionFinish": true
    }
  ]
}

I checked the browser and found that it connected to the Internet directly. Did I make wrong somewhere?

**Comment by YevgeniyShunevych** [comment]
You put `proxy` section outside of `driver/options`, directy into `driver` section. But it should be in `options`:

```json
{
  "driver": {
    "type": "chrome",
    "options": {
      "arguments": [
        "incognito",
        "disable-3d-apis",
        "disable-accelerated-video",
        "disable-background-mode",
        "disable-gpu",
        "disable-plugins",
        "disable-plugins-discovery",
        "disable-translate",
        "disable-extensions",
        "start-maximized",
        "ignore-certificate-errors"
      ],
      "proxy": {
        "kind": "Manual",
        "httpProxy": "127.0.0.1:8888",
        "sslProxy": "127.0.0.1:8888"
      }
    }
  },
  "baseUrl": "https://www.google.com",
  "culture": "en-US",
  "logConsumers": [
    {
      "type": "console",
      "minLevel": "Trace",
      "sectionFinish": true
    }
  ]
}
```

**Comment by siquylee** [comment]
Thanks, it works fine.

**Comment by YevgeniyShunevych** [comment]
Welcome.
