### ISSUE TITLE
[Q] It is possible to override json file driver globalAdditionalCapabilities from code ? 

### ISSUE THREAD

**Issue by goblinmaks** [atata-framework/atata-configuration-json#34]
When using selenoid is possible to set TestName as global capability [Selenoid Custom Test Name](https://aerokube.com/selenoid/latest/#_custom_test_name_name). Is it possible to override this key from code to set different test name for each test case ? 
Thanks,

**Comment by YevgeniyShunevych** [comment]
Basically, you need to invoke `AddAdditionalCapability("name", AtataContext.Current.TestName)` for WebDriver options. You can try something like this:

```cs
AtataContext.Configure().
    UseRemoteDriver().
        //...
        WithOptions<ChromeOptions>().
        WithOptions(x => x.AddAdditionalCapability("name", AtataContext.Current.TestName)).
        //...
```

Please share your `AtataContext` initialization code, if it doesn't work.

**Comment by goblinmaks** [comment]
I'm use json config to initialize and want to set current test name as AdditionalCapability. 

![image](https://user-images.githubusercontent.com/1436234/76543337-0bd79480-648f-11ea-8eeb-add72bc9a4c8.png)

Thanks,

**Comment by YevgeniyShunevych** [comment]
OK. Please try this way:

```cs
AtataContext.GlobalConfiguration.
    ApplyJsonConfig(@"...json").
    UseDriver(DefaultBrowserAlias);

var remoteDriverBuilder = AtataContext.GlobalConfiguration.BuildingContext.DriverFactoryToUse as RemoteDriverAtataContextBuilder;

if (remoteDriverBuilder != null)
    remoteDriverBuilder.WithOptions(x => x.AddAdditionalCapability("name", AtataContext.Current.TestName));
```

**Comment by goblinmaks** [comment]
Looks good, but do not work =)
Because it is GlobalAdditionalCapability and should pass as 
`x.AddAdditionalCapability("name", AtataContext.Current.TestName, global : true)`
But overloaded method with isGlobal parameter is missed in abstract DriverOptions class. 
![image](https://user-images.githubusercontent.com/1436234/76652557-81b32d00-656f-11ea-9820-0c9af96f65eb.png)

In this library code you used fabric to define concrete DriverType  that provide possibility to set AdditionalCapability as global. 

Thanks,

**Comment by YevgeniyShunevych** [comment]
OK, got it. Let's try to do it this way:

```cs
AtataContext.GlobalConfiguration.
    ApplyJsonConfig(@"...json").
    UseDriver(DefaultBrowserAlias);

var remoteDriverBuilder = AtataContext.GlobalConfiguration.BuildingContext.DriverFactoryToUse as RemoteDriverAtataContextBuilder;

if (remoteDriverBuilder != null)
{
    remoteDriverBuilder.WithOptions(options =>
    {
        string capabilityName = "name";
        string capabilityValue = AtataContext.Current.TestName;

        (options as ChromeOptions)?.AddAdditionalCapability(capabilityName, capabilityValue, true);
        (options as FirefoxOptions)?.AddAdditionalCapability(capabilityName, capabilityValue, true);
        (options as InternetExplorerOptions)?.AddAdditionalCapability(capabilityName, capabilityValue, true);
        (options as OperaOptions)?.AddAdditionalCapability(capabilityName, capabilityValue, true);
    });
}
```

If it also doesn't work for you, please share your driver JSON configuration to see the whole picture.

**Comment by goblinmaks** [comment]
Currently working with

```
AtataContext.GlobalConfiguration.
    ApplyJsonConfig(@"...json").
    UseDriver(DefaultBrowserAlias);

var remoteDriverBuilder = AtataContext.GlobalConfiguration.BuildingContext.DriverFactoryToUse as RemoteDriverAtataContextBuilder;

if (remoteDriverBuilder != null)
{
   remoteDriverBuilder.WithGlobalCapability("name", "TestName");
}
```

**Comment by YevgeniyShunevych** [comment]
Glad that you found that new `WithGlobalCapability` method.

You know, I was also thinking to provide the functionality to use some templated variables in JSON for `TestName` and probably some others:

```json
"globalAdditionalCapabilities": { 
  "name": "{test-name}"
}
```

I guess it will be useful, keeping all configuration in JSON.
