### ISSUE TITLE
Hide console window of chromedriver.exe

### ISSUE THREAD

**Issue by siquylee** [atata-framework/atata-configuration-json#41]
Using code, I could hide console window of chromedriver.exe as suggested [here](https://github.com/atata-framework/atata/issues/291). How can I do this with JSON config?

**Comment by YevgeniyShunevych** [comment]
This should work:

```js
{
  "driver": {
    "type": "chrome",
    "service": {
      "hideCommandPromptWindow": true
    }
  }
}
```

**Comment by siquylee** [comment]
Thanks, it works fine now !!!
