### ISSUE TITLE
Nunit-related exception occurs when using Atata-Config-Json in a Atata project built to use Xunit instead of Nunit

### ISSUE THREAD

**Issue by mamift** [atata-framework/atata-configuration-json#86]
Hello

I have this strange error occuring saying my project is missing nunit when I've built a testing project to use *Atata* and *Atata.Configuration.Json*.

The exception is **An exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code. Could not load file or assembly 'nunit.framework, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.**

I've built a minimal project (located here: https://github.com/mamift/AtataXunitExceptionThingie) that reproduces the error and the stack trace points to this line in the minimal project I set up:
https://github.com/mamift/AtataXunitExceptionThingie/blob/5dd545c142ed79f69e369d375f8c4529a7b72731/AtataXunitExceptionThingie/WhyDoesNunitExceptionThrow/SimpleUiTestsFixture.cs#L23

What I did was basically use the **Atata NUnit Advanced Test Project** as a project template:
![image](https://user-images.githubusercontent.com/2508444/172745883-12200e88-9e89-41a1-8c37-a6dc211c4055.png)

And then used the code in the Atata Xunit sample project (https://github.com/atata-framework/atata-samples/tree/master/Xunit/AtataSamples.Xunit) to replace Nunit with Xunit. But as I used the Advanced Test project template, it also brought in the `Atata.Configuration.Json` nuget package, which seems to be causing the error. 

Is `Atata.Configuration.Json` not compatible with Xunit? I would really like to use the Json config library with my Atata Xunit tests.

**Comment by YevgeniyShunevych** [comment]
Hello,

Thanks for providing the repository. It was easy to reproduce and find a cause of your issue. There is `"useAllNUnitFeatures": true,` left in `Atata.json` file related to NUnit. Also if you removed a reference to NLog and don't want that logging, you also need to remove `"nlog-file"` log consumer from config. Basically, the highlighted lines should be removed <https://github.com/mamift/AtataXunitExceptionThingie/blob/2debdd1ba0208c5b7f3b11b2df27913254b5c99e/AtataXunitExceptionThingie/WhyDoesNunitExceptionThrow/Atata.json#L25-L30>.

**Comment by mamift** [comment]
Aha, thank you so much for that. I would've kept using Nunit but need access to Xunit's integration testing facilities. It now works!

**Comment by YevgeniyShunevych** [comment]
You are welcome.
