### ISSUE TITLE
Initialize config global and current from object

### ISSUE THREAD

**Issue by wolvi19** [atata-framework/atata-configuration-json#91]
Is there any way to initialize JsonConfig global and current using config object instead of a file? 

I want to build configuration based on config file, user secrets and environment variables. I am not able to do it directly because of two reasons:
1. There is no implementation in AtataContextBuilder to handle user secrets
2. Using environment variables in config files will throw exception when variable is not defined - I would rather have null value if env variable does not exist so it can be set from other source.

To workaround it, I tried to use ConfigurationBuilder to create config object and set is as follows:
![image](https://user-images.githubusercontent.com/37906829/180419558-586af526-8df9-4779-90fa-67283dcc9c56.png)

However it will only apply values to the context which will not have any custom properties accessible and TestConfig.Global will be null.

I checked the implementation and I am wondering if there is any reason why the below method is so limited:

![image](https://user-images.githubusercontent.com/37906829/180419987-eb4b96d7-adf0-4b71-9146-f655cee3ee14.png)

I would love to have it similar to the one that accepts filePath:

![image](https://user-images.githubusercontent.com/37906829/180420069-b3dba666-27a0-49ff-a5db-9e73b66abd6f.png)

I tried to implement my own extension method in my project but I can't access internal classes like JsonConfigManager and I don't want to duplicate the code and adjust it on framework changes.

For now, I made some workaround to serialize built config to json, save it to file and pass to ApplyJsonConfig(filePath) method but  doing that I have a file stored with secret values so it's not desired approach. Do you have any suggestion how to do it differently?

**Comment by YevgeniyShunevych** [comment]
I created a repository https://github.com/YevgeniyShunevych/atata-samples-json-extended-configuration where I put together a couple of approaches of extended configuration. Please check out [SetUpFixture.cs](https://github.com/YevgeniyShunevych/atata-samples-json-extended-configuration/blob/main/AtataSamples.JsonExtendedConfiguration/SetUpFixture.cs) and other files.

The main idea is that you can extend your `JsonConfig<T>.Global` after you applied it in `GlobalSetUp`. There you can use any way of getting configuration values.

```cs
// Read and set configuration from TestContext:
AtataConfig.Global.Username = TestContext.Parameters.Get("TestUsername", AtataConfig.Global.Username);
AtataConfig.Global.Password = TestContext.Parameters.Get("TestPassword", AtataConfig.Global.Password);

// Read and set configuration from environment variables:
AtataConfig.Global.Username = Environment.GetEnvironmentVariable("TestUsername") ?? AtataConfig.Global.Username;
AtataConfig.Global.Password = Environment.GetEnvironmentVariable("TestPassword") ?? AtataConfig.Global.Password;

// Read and set configuration through ConfigurationBuilder from environment variables, user secrets, etc.:
var configuration = new ConfigurationBuilder()
    .AddEnvironmentVariables()
    .AddUserSecrets<SetUpFixture>()
    .Build();

configuration.Bind(AtataConfig.Global);

// Another alternative approach is to add custom variables:
AtataContext.GlobalConfiguration.AddVariable("key", "val");
// You can get the value in the test this way:
// AtataContext.Current.Variables["key"];

// Additional recommendation is to mask secret strings in log:
AtataContext.GlobalConfiguration.AddSecretStringToMaskInLog(AtataConfig.Global.Password);
```

But the common and recommended approach for multiple environments is to use different config files, like [Atata.local.json](https://github.com/YevgeniyShunevych/atata-samples-json-extended-configuration/blob/main/AtataSamples.JsonExtendedConfiguration/Atata.local.json) and [Atata.uat.json](https://github.com/YevgeniyShunevych/atata-samples-json-extended-configuration/blob/main/AtataSamples.JsonExtendedConfiguration/Atata.uat.json). Where in `Atata.local.json` you can hard-code credentials but for UAT/PreProd/Prod environments you may consider to reference credentials through "{env:...}" variables.

Please let me know if those approaches don't work for you. Maybe I didn't understand your issue completely.

**Comment by YevgeniyShunevych** [comment]
Additionally, I can say that for Atata v3 I want to use `ConfigurationBuilder` instead of Atata.Configuration.Json. So such things like using environment variables or user secrets will be easier to apply. But it is a far future.

**Comment by wolvi19** [comment]
Thanks a lot for the answer. I am able to solve my problem using existing functionalities, maybe not in the purest way but it works :) I am looking forward to Atata v3 so it can be simplified. Nevertheless, great work on the framework
