### ISSUE TITLE
Start driver service on specified port

### ISSUE THREAD

**Issue by szymonkl** [atata-framework/atata-configuration-json#92]
Is there any possibility to specify port where driver service will be started? For now different port is chosen every test run. Due to proxy settings on my machine I'm getting an error:
` OpenQA.Selenium.WebDriverException : Cannot start the driver service on http://localhost:55328/`

To fix the problem I need to set environment variable NO_PROXY=localhost

I would like to bypass proxy for the port which driver service is running, but I don't know what port it is. I checked that there is possibility to specify ignored ports using `portsToIgnore` option, but is there any possibility to specify port where driver should be started?

**Comment by YevgeniyShunevych** [comment]
There is no option to specify port explicitly for [ChromeDriverService](https://github.com/SeleniumHQ/selenium/blob/trunk/dotnet/src/webdriver/Chrome/ChromeDriverService.cs) and similar classes in WebDriver.

I don't know, maybe you can take a look at Selenium Grid or Selenoid to run a driver through them.

**Comment by szymonkl** [comment]
OK, thank you for the response
